# Generated by Django 5.0 on 2024-11-04 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='اسم الكفيل', max_length=255)),
                ('residence_location', models.CharField(help_text='مكان الاقامة', max_length=255)),
                ('primary_phone', models.CharField(help_text='رقم الهاتف', max_length=15)),
                ('secondary_phone', models.CharField(blank=True, help_text='رقم هاتف آخر', max_length=15, null=True)),
                ('sponsorship_amount', models.IntegerField(choices=[(700, '700 دينار شهريا'), (600, '600 دينار شهريا'), (500, '500 دينار شهريا'), (400, '400 دينار شهرياً'), (300, '300 دينار شهرياً'), (200, '200 دينار شهرياً'), (100, '100 دينار شهريا')], help_text='قيمة الكفالة  في الشهر')),
                ('custom_amount', models.IntegerField(blank=True, help_text='في حال اخترت قيمة أكبر من 700 دينار يرجى كتابة القيمة', null=True)),
                ('payment_frequency', models.CharField(choices=[('yearly', 'سنوي'), ('semi_annual', 'نصف سنوي'), ('quarterly', 'ربع سنوي'), ('monthly', 'شهري')], help_text='يكون تسليم  الكفالة بشكل', max_length=20)),
                ('initial_payment_timing', models.CharField(choices=[('this_month', 'بداية من هذا الشهر'), ('next_month', 'بداية من الشهر القادم')], help_text='موعد تسليم الدفعة الاولى من الكفالة', max_length=20)),
                ('payment_method', models.CharField(choices=[('cash', 'نقدي'), ('exchange_office', 'التحويل عن طريق مكاتب الصرافة الخاصة'), ('bank_transfer', 'التحويل المصرفي'), ('card', 'البطاقة المصرفية')], help_text='ما وسيلة الدفع المناسبة لك', max_length=20)),
                ('orphan_selection', models.CharField(choices=[('self', 'اريد اختيار اليتيم بنفسي'), ('campaign_assigned', 'افوض الحملة في اختيار اليتيم وفق المتبع لديها وابلاغي بالمعلومات'), ('no_info', 'غير مهتم بالحصول على معلومات عن اليتيم مع متابعة تسليم دفعات الكفالة')], help_text='اختيار اليتيم', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True, help_text='تاريخ تقديم النموذج')),
            ],
        ),
    ]
