# Generated by Django 5.0 on 2024-11-07 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='residence_location',
            field=models.CharField(choices=[('Misurata', 'مصراتة'), ('Tripoli', 'طرابلس'), ('Zletin', 'زليتن'), ('Alkhoms', 'الخمس'), ('Banghazi', 'بنغازي'), ('Msallata', 'مسلاتة'), ('Alzzawya', 'الزاوية')], help_text='مكان الاقامة', max_length=255),
        ),
    ]
