# Generated by Django 5.0 on 2024-11-09 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_sponsor_residence_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='initial_payment_timing',
            field=models.CharField(choices=[('بداية من هذا الشهر', 'بداية من هذا الشهر'), ('بداية من الشهر القادم', 'بداية من الشهر القادم')], help_text='موعد تسليم الدفعة الاولى من الكفالة', max_length=200),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='orphan_selection',
            field=models.CharField(choices=[('اريد اختيار اليتيم بنفسي', 'اريد اختيار اليتيم بنفسي'), ('افوض الحملة في اختيار اليتيم وفق المتبع لديها وابلاغي بالمعلومات', 'افوض الحملة في اختيار اليتيم وفق المتبع لديها وابلاغي بالمعلومات'), ('غير مهتم بالحصول على معلومات عن اليتيم مع متابعة تسليم دفعات الكفالة', 'غير مهتم بالحصول على معلومات عن اليتيم مع متابعة تسليم دفعات الكفالة')], help_text='اختيار اليتيم', max_length=200),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='payment_frequency',
            field=models.CharField(choices=[('سنوي', 'سنوي'), ('نصف سنوي', 'نصف سنوي'), ('ربع سنوي', 'ربع سنوي'), ('شهري', 'شهري')], help_text='يكون تسليم  الكفالة بشكل', max_length=100),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='payment_method',
            field=models.CharField(choices=[('نقدي', 'نقدي'), ('التحويل عن طريق مكاتب الصرافة الخاصة', 'التحويل عن طريق مكاتب الصرافة الخاصة'), ('التحويل المصرفي', 'التحويل المصرفي'), ('البطاقة المصرفية', 'البطاقة المصرفية')], help_text='ما وسيلة الدفع المناسبة لك', max_length=200),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='residence_location',
            field=models.CharField(choices=[('مصراتة', 'مصراتة'), ('طرابلس', 'طرابلس'), ('زليتن', 'زليتن'), ('الخمس', 'الخمس'), ('بنغازي', 'بنغازي'), ('مسلاتة', 'مسلاتة'), ('الزاوية', 'الزاوية')], help_text='مكان الاقامة', max_length=255),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='sponsorship_amount',
            field=models.IntegerField(choices=[(700, '700'), (600, '600'), (500, '500'), (400, '400'), (300, '300'), (200, '200'), (100, '100')], help_text='قيمة الكفالة  في الشهر'),
        ),
    ]
